add note about making bookmarks for things like monitoring tools and ssh connections
alicegoldfuss/oncall-handbook pull request #17
Opened 2016-11-29 08:50 UTC by zadr

Wasn't sure where to put this, and it seems to flow reasonably well in the middle of the existing on-call setup section, but the side effect that was that the following lines had their numbers changed too. Oops.

I thought about linking to steps for how to autostart ssh bookmarks on [mac](http://osxdaily.com/2012/06/03/create-ssh-bookmarks-in-terminal-for-mac-os-x/) and [ubuntu](http://superuser.com/questions/198015/open-gnome-terminal-programmatically-and-execute-commands-after-bashrc-was-execu) (well, `gnome-terminal`), but the rest of the page is platform-agnostic, so I erred on the side of sticking with the quo.

2016-11-29 19:36 UTC, alicegoldfuss requested changes

2016-11-29 19:36 UTC, alicegoldfuss commented on on_call_kit.md
> +7. Consider making bookmarks for everything. Save that group of browser tabs with the recipes for restarting things and monitoring tools ordered the way you like it. If there's a set of boxes you lik
Do you have a guide for auto-sshing that you can link in?

2016-11-29 19:42 UTC, zadr commented on on_call_kit.md
> +7. Consider making bookmarks for everything. Save that group of browser tabs with the recipes for restarting things and monitoring tools ordered the way you like it. If there's a set of boxes you lik
sure. mentioned a few in the PR notes as possibilities (one for mac and another gnome-based env's like ubuntu), but don't know of any for KDE's `konsole`, or any of the *BSD's. can leave that blank for others to fill in, i suppose.

2016-11-30 00:16 UTC, alicegoldfuss commented on on_call_kit.md
> +7. Consider making bookmarks for everything. Save that group of browser tabs with the recipes for restarting things and monitoring tools ordered the way you like it. If there's a set of boxes you lik
Ah, should have read the notes more thoroughly! You can just put in a parenthesis like (here's one for Mac OS and Ubuntu) and let others fill in other OSes.

2016-11-30 07:34 UTC, alicegoldfuss commented
Thank you!

2016-11-30 07:34 UTC, merged